### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by moh1122** [hypertrack/hypertrack-live-ios#4]
hello
I cant build the project its giving errors
I already did pod install also it succeeded but building the project is giving errors the error is error: redefinition of module 'zlib'

**Comment by moh1122** [comment]
error: could not build Objective-C module 'Gzip'

**Comment by ravijain412** [comment]
@moh1122:  are you using Xcode 8, if yes then you need to make a change in Podfile. 
use ```   pod 'HyperTrack', '0.4.56'```.  And if you are using Xcode 9 then make a change in  Podfile according to https://docs.hypertrack.com/sdks/ios/setup.html#for-xcode-9

**Comment by moh1122** [comment]
im using xcode 9 and i added:
use_frameworks!

target 'AppName' do
   pod 'HyperTrack'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end

        Dir.glob('Pods/SQLite.swift/Sources/SQLite/**/*.swift').each { |path|
            begin
                text = File.read(path)
                text = text.gsub(/import CSQLite/, 'import SQLite3')
                File.open(path, 'w') { |file| file.puts text }
                rescue Exception
                puts "Unable to patch #{path}: #{$!}"
            end
        }
    end
end


to the pod file and still got errors
I removed what was in the pod file before adding this

**Comment by ravijain412** [comment]
@moh1122  : can you share your Podfile.lock

**Comment by moh1122** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def hypertrack_pods
    pod 'HyperTrack'
    #pod 'HyperTrack.local', :path => '~/hypertrack-ios-v3/HyperTrack.local.podspec'
end



target 'htlive-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  hypertrack_pods
  pod 'FSCalendar'
  pod 'PhoneNumberKit', '~> 1.2'
  pod 'MBProgressHUD'
  pod 'Branch'
  pod 'Crashlytics'


  post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end

        Dir.glob('Pods/SQLite.swift/Sources/SQLite/**/*.swift').each { |path|
            begin
                text = File.read(path)
                text = text.gsub(/import CSQLite/, 'import SQLite3')
                File.open(path, 'w') { |file| file.puts text }
                rescue Exception
                puts "Unable to patch #{path}: #{$!}"
            end
        }
    end
end

**Comment by ravijain412** [comment]
@moh1122: Hey, Can you quickly try a ```pod update``` and let me know if that helps.

**Comment by moh1122** [comment]
thnk u 
i have one error now which is Use of unresolved identifier 'YOUR_PUBLISHABLE_KEY'

**Comment by ravijain412** [comment]
Hey @moh1122  : you have to sign up on hypertrack and get the publishable key.
Sign up at https://www.hypertrack.com/signup
