### ISSUE TITLE
Can I access app without enabling location service?

### ISSUE THREAD

**Issue by moh1122** [hypertrack/hypertrack-live-ios#5]
Hello
Can I access app without enabling location service?

**Comment by ravijain412** [comment]
@moh1122 : Yes, we need location permissions in the app to give value through hypertrack sdk.

**Comment by moh1122** [comment]
how can I do that

**Comment by ravijain412** [comment]
@moh1122 : is the app stuck at the enable location service ? If you have denied location permissions than you need to go to app settings to enable it. We will need 'Always' permission for location.

**Comment by moh1122** [comment]
I understand that. What im asking for is that can I access the app without giving full permission to the location for the app. 
What i want is to launch the app and go inside it without giving full location permission.

**Comment by SARJANUSU** [comment]
Saya tidak mengerti tentang IT ,bisakah saya dapatkan yg sudah dalam bentuk aplikasi? Caranya

**Comment by moh1122** [comment]
?

**Comment by ravijain412** [comment]
@moh1122: yes, you can change the code according to your needs and use the HyperTrack Live app. HyperTrack SDK needs location permission to work.
